#!/bin/sh -e

if [ $# != 1 ]; then
    printf "Usage: $0 source-file\n"
    exit 1
fi

if [ -e plasm.bin ]; then
    plasm_bin=./plasm.bin
else
    plasm_bin=plasm.bin
fi
source="$1"
pp_source="${source%.*}-pp.${source##*.}"
papp "$source" > "$pp_source"
$plasm_bin "$pp_source"
mv "${pp_source%.*}.bin" "${source%.*}.bin"

