#!/bin/sh -e

if [ $# != 1 ]; then
    printf "Usage: $0 source-file\n"
    exit 1
fi

source=$1
pp_source=${source%.*}-pp.${source##*.}
papp $source > $pp_source
plasm.bin $pp_source > ${source%.epc}.bin

